### PR TITLE
Local

### PR DESCRIPTION
**Pull request by smoscar**
This gives simple support for pages

Since the theme is user experience driven, and pretty permalinks are needed anyways, posts and pages need to have a different URL structure for this implementation to work. This allows the Angular router to quickly identify which component should be loaded and opens up the door for future additions like multiple page templates, categories, search, etc.

Note: A path matcher is used to test the posts against the permalink URL structure set in the WP backend

### CODE REVIEW

**Comment by bradleykirby** [comment]
Thanks for the PR! Lots of changes here so I haven't had time to review it extensively yet. My primary concern with what I have seen is with the pattern matcher for the post urls. I specifically didn't go that route when I was writing the routing code because of the details I laid out in this blog post: https://blog.wallacetheme.com/wordpress-theme-rest-api.

Even so, it's possible that that approach will still work. I'll try to give it a more thorough review in the coming days.

**Comment by smoscar** [comment]
Looking forward to it

I am following the same approach. The URL matcher is only used for the initial load

Let me know what you think

**Comment by smoscar** [comment]
Hey man, 

After carefully reading your post (and the other routing options you quoted there), I understood what you were trying to achieve and agree that this approach makes a lot more sense

In my latest commit, I removed the need for the url matcher and even the initial wildcard route so that it can be used for a 404 page.

Let me know what you think

**Comment by bradleykirby** [comment]
Very nice. I really appreciate all the work you've put into this PR and understanding the codebase. Going to review and most likely merge this week.

**Pull request merged**
